<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function createAlphabeticalQueryBuilder(){
        return $this->createQueryBuilder('category')
            ->orderBy('category.name', 'ASC');
    }
}
