<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByUser(User $user){
        return $this->createQueryBuilder('todo')
            ->andWhere('todo.user = :user')
            ->setParameter('user', $user)
            //->leftJoin('todo.user', 'user')
            ->getQuery()
            ->execute();
    }
}
